# Generated by Django 3.2.19 on 2023-09-03 09:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhtotDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.IntegerField(null=True, verbose_name='文件id号')),
                ('user_id', models.IntegerField(null=True, verbose_name='用户id号')),
                ('file_name', models.CharField(max_length=128, verbose_name='文件名称')),
                ('file_type', models.IntegerField(null=True, verbose_name='文件类型')),
                ('file_state', models.CharField(max_length=64, verbose_name='文件状态')),
                ('file_desc', models.CharField(max_length=256, verbose_name='文件描述')),
                ('file_path', models.CharField(max_length=256, verbose_name='文件路径')),
                ('upload_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
